name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # You can adjust this to your preferred Node.js version

    - name: Install dependencies
      run: npm ci  # This uses package-lock.json for a clean install

    - name: Create public directory
      run: mkdir -p public

    - name: Create Firebase config
      run: |
        echo "const firebaseConfig = {" > public/firebase-config.js
        echo "  apiKey: '${{ secrets.FIREBASE_API_KEY }}'," >> public/firebase-config.js
        echo "  authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}'," >> public/firebase-config.js
        echo "  projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'," >> public/firebase-config.js
        echo "  storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}'," >> public/firebase-config.js
        echo "  messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'," >> public/firebase-config.js
        echo "  appId: '${{ secrets.FIREBASE_APP_ID }}'" >> public/firebase-config.js
        echo "};" >> public/firebase-config.js
        echo "export default firebaseConfig;" >> public/firebase-config.js

    - name: Build the project
      run: npm run build  # Adjust this if your build command is different

    - name: List contents of public directory
      run: ls -l public

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
